//
//  EditScriptConverter+UITableView.swift
//  EditDistance
//
//  Created by Kazuhiro Hayashi on 2/19/17.
//  Copyright © 2017 Kazuhiro Hayashi. All rights reserved.
//

import UIKit

public extension EditScriptConverterProxy where Converter: UITableView {
    
    /// Updates this UICollectionView object with EditDistanceContainer object.
    ///
    /// EditScript array in the object is converted to insertRows(at:,with:) and deleteRows(at:,with:) of UITableView
    /// - Parameter container: EditDistanceContainer object generated by EditDistance
    public func reload<T>(with container: EditDistanceContainer<T>) {
        _converter.beginUpdates()
        container.editScripts.forEach({ (script) in
            switch script {
            case .add(_, let indexPath):
                _converter.insertRows(at: [indexPath], with: .fade)
            case .delete(_, let indexPath):
                _converter.deleteRows(at: [indexPath], with: .fade)
            case .common:
                break
            }
        })
        _converter.endUpdates()
    }
}
